
import React from 'react';
import { AlertTriangle } from 'lucide-react';

const DisclaimerSection = () => {
  return (
    <section id="disclaimer" className="py-20 relative bg-cyber-dark/50">
      <div className="container mx-auto px-4 md:px-6">
        <div className="max-w-4xl mx-auto glassmorphism rounded-lg p-8 border border-cyber-blue/30">
          <div className="flex items-center mb-6">
            <AlertTriangle className="h-6 w-6 text-cyber-yellow mr-3" />
            <h2 className="text-2xl md:text-3xl font-bold text-white">Legal Disclaimer</h2>
          </div>
          
          <div className="space-y-4 text-gray-300">
            <p>
              Social Safety Net GPT ("Homie") is provided as an informational resource only. While we strive to provide accurate and helpful information, the content generated by our AI is not a substitute for professional advice or emergency services.
            </p>
            
            <p>
              In case of emergency, please contact appropriate emergency services such as 911 (US), 999 (UK), or your local emergency number immediately.
            </p>
            
            <h3 className="text-xl font-semibold text-white mt-6 mb-2">Information Accuracy</h3>
            <p>
              The information provided by Social Safety Net GPT is sourced from various online resources and databases. While we make every effort to ensure the accuracy and timeliness of information, we cannot guarantee that all information is current or complete. We recommend verifying any critical information directly with the service providers.
            </p>
            
            <h3 className="text-xl font-semibold text-white mt-6 mb-2">No Professional Advice</h3>
            <p>
              The content provided by Social Safety Net GPT should not be construed as legal, medical, financial, or other professional advice. Users should consult qualified professionals for advice tailored to their specific situations.
            </p>
            
            <h3 className="text-xl font-semibold text-white mt-6 mb-2">Limitation of Liability</h3>
            <p>
              AI WEB TOOLS LLC, its affiliates, and partners shall not be liable for any direct, indirect, incidental, consequential, or special damages arising out of or in any way connected with the use of Social Safety Net GPT, regardless of whether such damages are based on contract, tort, strict liability, or other theories of liability.
            </p>
            
            <h3 className="text-xl font-semibold text-white mt-6 mb-2">External Links</h3>
            <p>
              Social Safety Net GPT may provide links to external websites or resources. These links are provided for convenience only, and we do not endorse, control, or make any representations regarding the content or accuracy of these external sites.
            </p>
            
            <p className="mt-6 text-sm text-gray-400">
              By using Social Safety Net GPT, you acknowledge that you have read, understood, and agree to this disclaimer.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default DisclaimerSection;
